"""
Fig 2: MAB tradeoff across arm differences (T=785, two-arm Bernoulli).
Three panels: power loss from UR, reward loss from TS, prop superior.

Data source: data/mab_tradeoff_results.json
  (generated by mab-simulation/scripts/thesis_figures/postdiff_fig1_reward_power_tradeoff.py)

Output: latex/figures/fig2_mab_tradeoff_sweep.pdf
"""
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[0].parent
DATA = ROOT / "data" / "mab_tradeoff_results.json"
FIG_DIR = ROOT / "latex" / "figures"

with open(DATA) as f:
    raw = json.load(f)

arm_diffs = np.array(raw["config"]["arm_diffs"])
metrics = raw["metrics"]

KEY_MAP = {
    "EpsTS (0.345)": r"$\varepsilon$-TS (0.345)",
    "TSPostDiffUR (0.110)": "TS-PostDiff (0.110)",
    "TSProbClip (0.425)": "TS-ProbClip (0.425)",
}
metrics = {KEY_MAP.get(k, k): v for k, v in metrics.items()}

ALGO_ORDER = [
    "TS",
    "UR",
    r"$\varepsilon$-TS (0.345)",
    "TS-PostDiff (0.110)",
    "TS-ProbClip (0.425)",
]

STYLES = {
    "TS":                        dict(color="black",    marker="*", linestyle="--", linewidth=1.5),
    "UR":                        dict(color="gray",     marker="d", linestyle="--", linewidth=1.0),
    r"$\varepsilon$-TS (0.345)": dict(color="green",    marker="o", linestyle="-",  linewidth=1.5),
    "TS-PostDiff (0.110)":       dict(color="#DAA520",   marker="s", linestyle="-",  linewidth=1.5),
    "TS-ProbClip (0.425)":       dict(color="purple",   marker="^", linestyle="-",  linewidth=1.5),
}

ur_power = np.array(metrics["UR"]["power"])
ts_reward = np.array(metrics["TS"]["reward"])

fig, axes = plt.subplots(3, 1, figsize=(7, 12), sharex=True)

ax = axes[0]
for name in ALGO_ORDER:
    power = np.array(metrics[name]["power"])
    ax.plot(arm_diffs, ur_power - power, **STYLES[name], markersize=5, label=name)
ax.set_ylabel("Power Loss from UR")
ax.set_title("Relative Power Loss (UR baseline = 0)")
ax.grid(True, alpha=0.3)

ax = axes[1]
for name in ALGO_ORDER:
    reward = np.array(metrics[name]["reward"])
    ax.plot(arm_diffs, ts_reward - reward, **STYLES[name], markersize=5, label=name)
ax.set_ylabel("Reward Loss from TS")
ax.set_title("Relative Reward Loss (TS baseline = 0)")
ax.grid(True, alpha=0.3)

ax = axes[2]
for name in ALGO_ORDER:
    prop = np.array(metrics[name]["prop_opt"])
    ax.plot(arm_diffs, prop, **STYLES[name], markersize=5, label=name)
ax.set_ylabel("Prop Superior")
ax.set_xlabel("Arm Difference")
ax.set_title("Proportion Allocated to Superior Arm")
ax.grid(True, alpha=0.3)

handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc="lower center", ncol=3, fontsize=9,
           bbox_to_anchor=(0.5, -0.02))
fig.tight_layout(rect=[0, 0.03, 1, 1])

out = FIG_DIR / "fig2_mab_tradeoff_sweep.pdf"
fig.savefig(out, bbox_inches="tight")
plt.close(fig)
print(f"Saved to {out}")
