"""
Fig 3: Factorial tradeoff across varying beta_1 (T=785, 2x3 design).
Four panels: power loss, reward loss, min eigenvalue, allocation to X1=1.

Data source: data/sweep_matched_results.csv
  (generated by claude_scripts/2026-04-02_power_analysis/sweep_matched.py)

Output: latex/figures/fig3_factorial_sweep.pdf
"""
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[0].parent
DATA = ROOT / "data" / "sweep_matched_results.csv"
FIG_DIR = ROOT / "latex" / "figures"

df = pd.read_csv(DATA)

ALGO_STYLE = [
    ("TS-linear",     "TS-linear",       "black",     "*",  "--"),
    ("UR",            "UR",              "gray",      "d",  "--"),
    ("AGTS+PD(P80)",  "AGTS+PostDiff",   "goldenrod", "s",  "-"),
    ("AG-TS(R=0.60)", "AG-TS (R=0.60)",  "green",     "o",  "-"),
    ("LinUCB(60)",    "LinUCB (a=60)",   "purple",    "^",  "-"),
]


def get_series(algo_name, col):
    sub = df[df["Algorithm"] == algo_name].sort_values("beta_1")
    return sub["beta_1"].values, sub[col].values


_, ur_power = get_series("UR", "Pow_X1_ait")
_, ts_reward = get_series("TS-linear", "Mean_Reward")

fig, axes = plt.subplots(4, 1, figsize=(7, 14), sharex=True)

ax = axes[0]
ax.set_title("Power Loss from UR (lower = better)", fontsize=11)
ax.set_ylabel("Power Loss from UR (%)")
for name, label, color, marker, ls in ALGO_STYLE:
    x, power = get_series(name, "Pow_X1_ait")
    ax.plot(x, ur_power - power, color=color, marker=marker, linestyle=ls,
            label=label, markersize=7)
ax.axhline(0, color="gray", linewidth=0.5, linestyle=":")
ax.legend(fontsize=8)

ax = axes[1]
ax.set_title("Reward Loss from TS-linear (lower = better)", fontsize=11)
ax.set_ylabel("Reward Loss from TS")
for name, label, color, marker, ls in ALGO_STYLE:
    x, reward = get_series(name, "Mean_Reward")
    ax.plot(x, ts_reward - reward, color=color, marker=marker, linestyle=ls,
            label=label, markersize=7)
ax.axhline(0, color="gray", linewidth=0.5, linestyle=":")
ax.legend(fontsize=8)

ax = axes[2]
ax.set_title("Mean Min Eigenvalue of X'X", fontsize=11)
ax.set_ylabel("Min Eigenvalue")
for name, label, color, marker, ls in ALGO_STYLE:
    x, eig = get_series(name, "Min_Eigenvalue")
    ax.plot(x, eig, color=color, marker=marker, linestyle=ls,
            label=label, markersize=7)
ax.legend(fontsize=8)

ax = axes[3]
ax.set_title("Proportion Allocated to $X_1 = 1$ Arms", fontsize=11)
ax.set_ylabel("Prop. $X_1 = 1$")
ax.set_xlabel(r"$\beta_1$ (true coefficient)")
for name, label, color, marker, ls in ALGO_STYLE:
    x, alloc = get_series(name, "Alloc_X1_best")
    ax.plot(x, alloc, color=color, marker=marker, linestyle=ls,
            label=label, markersize=7)
ax.axhline(0.5, color="gray", linewidth=0.5, linestyle=":", label="0.5 (uniform)")
ax.legend(fontsize=8)

plt.tight_layout()
fig.savefig(FIG_DIR / "fig3_factorial_sweep.pdf", bbox_inches="tight")
plt.close(fig)
print(f"Saved to {FIG_DIR / 'fig3_factorial_sweep.pdf'}")
